-- ============================================================================
-- V1_000 — Platform kernel
--
-- Cross-cutting tables used by every context: long-running operations, the
-- transactional outbox, idempotency keys, feature flags and platform-level
-- encryption keys.
--
-- Conventions (see docs/architecture/05-database-schema.md):
--   * uuid primary keys generated by the application
--   * timestamptz, always UTC
--   * enums as text + check constraint, so they can be extended safely
--   * no foreign keys across context boundaries
-- ============================================================================

create extension if not exists pgcrypto;
create extension if not exists citext;

-- ---------------------------------------------------------------------------
-- Operations: the observable unit of asynchronous work.
-- ---------------------------------------------------------------------------
create table plat_operations (
    id                       uuid primary key,
    organization_id          uuid,
    kind                     varchar(80)  not null,
    state                    varchar(20)  not null default 'PENDING'
                             check (state in ('PENDING','RUNNING','SUCCESS','FAILED','CANCELLED')),
    progress                 integer      not null default 0 check (progress between 0 and 100),
    resource_type            varchar(80),
    resource_id              uuid,
    request_idempotency_key  varchar(128),
    error_code               varchar(64),
    error_message            varchar(2000),
    attempts                 integer      not null default 0,
    lease_expires_at         timestamptz,
    started_at               timestamptz,
    finished_at              timestamptz,
    created_at               timestamptz  not null default now(),
    updated_at               timestamptz  not null default now(),
    version                  bigint       not null default 0
);

create index ix_plat_operations_org_state on plat_operations (organization_id, state);
create index ix_plat_operations_lease     on plat_operations (state, lease_expires_at);

comment on table plat_operations is
    'Long-running work returned as 202 Accepted. Written before the work starts so a customer can always ask what happened.';

-- ---------------------------------------------------------------------------
-- Transactional outbox.
-- ---------------------------------------------------------------------------
create table plat_outbox (
    id               uuid primary key,
    aggregate_type   varchar(80)  not null,
    aggregate_id     uuid,
    event_type       varchar(120) not null,
    event_version    integer      not null default 1,
    organization_id  uuid,
    correlation_id   varchar(64),
    occurred_at      timestamptz  not null,
    payload          jsonb        not null,
    published_at     timestamptz,
    attempts         integer      not null default 0,
    next_attempt_at  timestamptz,
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now(),
    version          bigint       not null default 0
);

create index ix_plat_outbox_pending on plat_outbox (published_at, next_attempt_at, occurred_at)
    where published_at is null;

comment on table plat_outbox is
    'Events written in the same transaction as the business change; drained asynchronously. Nothing is lost when the broker is down.';

-- ---------------------------------------------------------------------------
-- Idempotency.
-- ---------------------------------------------------------------------------
create table plat_idempotency_keys (
    id               uuid primary key,
    organization_id  uuid         not null,
    key              varchar(128) not null,
    method           varchar(10)  not null,
    path             varchar(512) not null,
    request_hash     varchar(64)  not null,
    response_status  integer,
    response_body    jsonb,
    completed        boolean      not null default false,
    expires_at       timestamptz  not null,
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now(),
    version          bigint       not null default 0,
    constraint uq_plat_idempotency_org_key unique (organization_id, key)
);

create index ix_plat_idempotency_expires on plat_idempotency_keys (expires_at);

-- ---------------------------------------------------------------------------
-- Feature flags. Evaluated server side only; never trusted from the client.
-- ---------------------------------------------------------------------------
create table plat_feature_flags (
    id               uuid primary key,
    key              varchar(120) not null unique,
    description      varchar(512),
    enabled          boolean      not null default false,
    rollout_percent  integer      not null default 0 check (rollout_percent between 0 and 100),
    plan_codes       text[]       not null default '{}',
    organization_ids text[]       not null default '{}',
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now(),
    version          bigint       not null default 0
);

-- Emergency kill switches and Phase-1 gated capabilities.
insert into plat_feature_flags (id, key, description, enabled, rollout_percent) values
    (gen_random_uuid(), 'platform.maintenance_mode',   'Read-only mode for the whole platform',            false, 0),
    (gen_random_uuid(), 'cms.scheduled_publishing',    'Schedule content releases for a future time',       true, 100),
    (gen_random_uuid(), 'deployment.canary',           'Canary deployment strategy',                       false, 0),
    (gen_random_uuid(), 'analytics.alerts',            'Metric alerting',                                    true, 100),
    (gen_random_uuid(), 'private.connector',           'Private deployment connector pairing',             false, 0);

-- ---------------------------------------------------------------------------
-- Platform-level encryption keys (wrapped DEKs). Tenant DEKs live on the
-- organization row.
-- ---------------------------------------------------------------------------
create table plat_encryption_keys (
    id            uuid primary key,
    key_id        varchar(64)  not null unique,
    wrapped_key   text         not null,
    algorithm     varchar(32)  not null default 'AES-256-GCM',
    primary_key   boolean      not null default false,
    created_at    timestamptz  not null default now(),
    updated_at    timestamptz  not null default now(),
    version       bigint       not null default 0
);

comment on column plat_encryption_keys.wrapped_key is
    'DEK wrapped by a KEK held in the configured secret store. Plaintext key material is never stored here.';

-- ---------------------------------------------------------------------------
-- Usage counters backing quota enforcement.
-- ---------------------------------------------------------------------------
create table plat_usage_counters (
    id               uuid primary key,
    organization_id  uuid         not null,
    quota_key        varchar(64)  not null,
    quantity         bigint       not null default 0,
    updated_at       timestamptz  not null default now(),
    constraint uq_plat_usage_org_key unique (organization_id, quota_key)
);

-- ---------------------------------------------------------------------------
-- updated_at maintenance.
-- ---------------------------------------------------------------------------
create or replace function plat_touch_updated_at() returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

do $$
declare t text;
begin
    foreach t in array array[
        'plat_operations','plat_outbox','plat_idempotency_keys','plat_feature_flags',
        'plat_encryption_keys'
    ] loop
        execute format('create trigger trg_%s_touch before update on %I for each row execute function plat_touch_updated_at()', t, t);
    end loop;
end $$;
